### ISSUE TITLE
Comprobar que el esquema de instalación se corresponde con el usado

### ISSUE THREAD

**Issue by PabloCastellano** [guifi/drupal-guifi#3]
PR relacionado: https://github.com/guifi/drupal-guifi/pull/1

A través del módulo Schema disponible en la web se puede generar el esquema actual de la BD. 
La tarea es comprobar si el resultado se corresponde con el contenido de la función guifi_schema() del archivo guifi.install.

Lo haría yo pero mi usuario no tiene permisos para acceder a http://guifi.net/en/admin/build/schema/inspect

**Comment by miquelmartos** [comment]
hecho!
