### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by lechucky** [guifi/drupal-guifi#38]
A while ago (Months!) you could search a node by its shortname, name, description, etc.
It seems that now the search box does not takes into acount the node name when finding results... 
Using "advanced search" does not help either
Searching a node by it's name is very useful, otherwise you have to go to your zone...
is it possible to fix this?

Thanks in advance

Examples:
Searching "CaldersMontardo22" (this is a node name) gets 2 results but the node itself [https://guifi.net/ca/node/57115] is not listed.
Searching "SFDB" (or SFDB* or SFDB%) does not get any result (SFDB is short for sant fruitos de bages, and a lot of nodes begin with this letters, see for example the list of connected nodes of one of it's supernodes: https://guifi.net/ca/dipositsfb)

**Comment by rogerpueyo** [comment]
Dear @lechucky ,

I guess this is something not related specifically to the drupal-guifi, but to the Drupal site itself. As far as I know, Drupal sort of creates a search index by crawling all the pages it has (including nodes, devices, etc.). I believe this search index creation stalled some time ago, this is why you search for a *very old* node you can find it (even if it has been deleted later), and why you don't see newly created nodes.

**Comment by rogerpueyo** [comment]
The index is being regenerated.

**Comment by lechucky** [comment]
Just checked, it works as espected now.
Thanks!

**Comment by rogerpueyo** [comment]
Great, @lechucky!
