### ISSUE TITLE
No hi ha cap link de logout

### ISSUE THREAD

**Issue by rgf1042** [guifi/drupal-guifi#39]
Amb la versió actual de guifi-drupal no hi trobem cap link per tal de fer un logout. Si mirem la versió del mòdul en Drupal 6 podem veure que al menú superior l'últim link ens serveix per aquest proposit.

**Comment by miquelmartos** [comment]
Parles del modul en desenvolupament de drupal7?
El menú que surt a la part alta de la web no te res a veure amb el modul drupal-guifi, allò son opcions pròpies del drupal.
En el meu entorn de proves de drupal7 hi ha aquest botó.

**Comment by rogerpueyo** [comment]
A mi em passa igual, no tinc el botó de logout ni la URL fa res.

@miquelmartos , a quina URL apunta el link de Logout al teu entorn de desenvolupament de Drupal7?

**Comment by rgf1042** [comment]
Si, parlo del mòdul de drupal7 en desenvolupament. Després d'haver fet altres comprovacions amb altres entorns de desenvolupament he vist que en cap d'ells hi apareixia. No obstant potser si que és alguna cosa de les nostres configuracions. Seguiré investigant :D

**Comment by miquelmartos** [comment]
El meu entorn es un docker al meu propi pc, no es accessible per a ningú mes que jo.
Estem parlant d'una funcionalitat de DRUPAL, no del mòdul que estem desenvolupant.
Centrem-nos en el modul please.

**Comment by rogerpueyo** [comment]
Doncs fora :)

**Comment by rogerpueyo** [comment]
@rgf1042 El problema no és específic del mòdul drupal-guifi, sinó de l'actualització de Drupal 6 a Drupal 7.
