### ISSUE TITLE
use recaptcha on registration

### ISSUE THREAD

**Issue by ghost** [guifi/drupal-guifi#40]
Some users have difficulties to manage guifi captcha.

Facilitate registration of new users with [recaptcha](https://www.google.com/recaptcha/intro/)

As an example, [freenode's webchat](http://webchat.freenode.net/) uses it for anonymous users

**Comment by miquelmartos** [comment]
El captcha o recaptcha no te res a veure amb el modul guifi.net per drupal.
No es aquí on s'ha de notificar això.
Tanco.

**Comment by ghost** [comment]
Hola Miquel,

Dos cosetes al respecte:

1. Si estàs / esteu d'acord (consens) que seria bo implementar recaptcha

> No es aquí on s'ha de notificar això.

2. On s'hauria de vehicular per fer-ho possible?

**Comment by rogerpueyo** [comment]
Hola @pedro-nonfree,

Com bé diu el Miquel, el recaptcha no té res a veure amb el mòdul Guifi.net per a Drupal. Per tant, tampoc és aquest el lloc on debatre-ho. T'emplaço a que ho facis a través de la llista guifi-dev, o bé a http://trac.guifi.net

SAX!

**Comment by ghost** [comment]
Tema debat, ok, llistes o trac

I en cas de estar implementat on es faria el pull request? Hi ha repositori git?

**Comment by ghost** [comment]
resposta:

https://llistes.guifi.net/sympa/arc/guifi-dev/2017-07/msg00023.html
