### ISSUE TITLE
[Portada] La pestanya "Articles recents" mostra el llistat de pàgines en vertical, no en horitzontal

### ISSUE THREAD

**Issue by rogerpueyo** [guifi/drupal-guifi#42]
Per exemple:

`

    23/8/17 SAX 2017, els dies 26 i 27 d'agost a Valls
    31/5/17 La Fundació aporta més documentació que demostra que les taxes de la Generalitat son discriminatòries i abusives
    25/5/17 Denuncia a la Generalitat de Catalunya per alentir el desplegament de la fibra òptica i afeblir la competència
    24/4/17 La Fundació Guifi.net esdevé membre de l'APC
    8/2/17 Guifi.net - Biblioteca de Perafita (Lluçanès)
    5/2/17 Univers Internet, curs 2016-2017. La maleta pedagógica.
    15/1/17 Xerrada "GuifiClot - Introducció a la xarxa d'internet en comú"
    10/1/17 Fibra òptica a granges d'Osona
    19/12/16 [Guifilab] Docker + Ansible el proper divendres 23 de desembre a Can Fugarolas
    18/10/16 Premis WiFi NOW: guifi.net entre els tres candidats en la categoria d'accessibilitat

    1
    2
    3
    4
    5
    6
    7
    8
    9
    …
    següent ›
    últim »

Més notícies
`

**Comment by miquelmartos** [comment]
Bones,
Cal veure a que es degut aquest problema però en qualsevol cas no es un problema del modul guifi.net per drupal6.
El que format del que surt en aquest apartat es defineix al Theme:  https://github.com/guifi/drupal-theme_guifinet2011 , segurament s'estan publicant articles en algun format que el theme no reconeix i per això es mostra malament.

**Comment by rogerpueyo** [comment]
Tens tota la raó, @miquelmartos . Ho moc a https://github.com/guifi/drupal-theme_guifinet2011/issues/1
